[package]
name = "hackattic_common"
version = "0.1.0"
authors = ["NMDanny <nmdanny@gmail.com>"]

[dependencies]
failure = "^0.1.1"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
reqwest = "^0.8.1"
log = "^0.4"
base64 = "^0.8.0"
hex = "^0.3.1"
lazy_static = "^1.0"
