[package]
name = "hackattic"
version = "0.1.0"
authors = ["NMDanny <nmdanny@gmail.com>"]

[dependencies]
hackattic_common = { path = "hackattic_common" }
hosting_git = { path = "hosting_git" }
jotting_jwts = { path = "jotting_jwts" }
[workspace]
